apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clo835
  region: "us-west-2"
  version: "1.19"

availabilityZones: ["us-west-2a" ,"us-west-2b" ,"us-west-2c"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 2
  instanceType: t3.small
  ssh:
    enableSsm: true
