apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongopvc-manual
spec:
  storageClassName: localstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  
  